version: '2'
services:
  nginx:
      build: "./nginx"
      links: ["node1", "node2"]
      ports: ["80:80"]
  node1:
      build:
        context: "./node"
        args:
          http_proxy: "${http_proxy}"
          https_proxy: "${https_proxy}"
      environment:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
        NODE_PATH: "lib"
        NODE_ENV: "production"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "password"
      links: ["postgres", "mongo"]
      ports: ["5000:5000"]
  node2:
      build:
        context: "./node"
        args:
          http_proxy: "${http_proxy}"
          https_proxy: "${https_proxy}"
      environment:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
        NODE_PATH: "lib"
        NODE_ENV: "production"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "password"
      links: ["postgres", "mongo"]
      ports: [5000]
  postgres:
      image: "postgres"
      environment:
          POSTGRES_USER: "admin"
          POSTGRES_PASSWORD: "password"
      ports: ["5432:5432"]
  mongo:
      image: mongo
      ports: ['27017:27017']
